name = "my-app"
compatibility_date = "2024-08-20"

[vars]
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNDYwMDNhZmEtNmNlZC00MWQ5LWE4ZGEtYjVlNGM2NzBjODgyIiwidGVuYW50X2lkIjoiYTIyZjQwOThlMWU2ODJjZjU3MTI1NDNkM2Q3YzNhZWU3ZjA3NjhkYzNiMmQ2M2UwNWI1NmU0YjM1MzMwMDUxZSIsImludGVybmFsX3NlY3JldCI6IjM0ZTM1NTVlLTcxZDYtNGJmZi1hZGZiLTY0MmM5ZDRiMDYxZCJ9.TSKplmrXqHUEraEYV_HKKrbV4DdOP4Q-vCfk1HHcE3w"
JWT_SECRET = "Vanshsecret"
